### PR TITLE
fix: Add file descriptor pool to storage

### LINKED ISSUE #119: Use file descriptor pool implementation to avoid limitations on Android
## Description

Our usage of `random-access-storage` and the number of hypercores that each peer has/syncs puts the application at reasonable risk of going over Android's limit for file descriptors (fixed at 1024 for Android).

`random-access-storage` has an undocumented [pool](https://github.com/random-access-storage/random-access-file/blob/master/index.js#L77-L79) implementation to address this, so that probably can fit the needs here.

## Tasks

- [ ] integrate `random-access-storage`'s file descriptor implementation (or some variation of that)

### PR DESCRIPTION
**Pull request by gmaclennan**
Add a file descriptor pool for core storage, fixes #119.

Needed a custom pool implementation, since the one on random-access-file is [currently broken](https://github.com/random-access-storage/random-access-file/pull/38)

### CODE REVIEW

File: tests/core-manager.js [hunk 1]
```diff
@@ -324,6 +329,63 @@ test('encryption', async function (t) {
...
+    const db = new Sqlite(':memory:')
+    const storage = name => new RandomAccessFile(path.join(tempPath, name))
+    const cm = new CoreManager({
+      db,
+      keyManager,
+      storage,
+      projectKey,
+      projectSecretKey
+    })
+    // -1 because we CoreManager creates a writer core already
```
Comment (achou11) [inline tests/core-manager.js:348]:
```suggestion
    // -1 because CoreManager creates a writer core already
```

File: tests/core-manager.js [hunk 2]
```diff
@@ -388,3 +450,19 @@ function bitfieldEquals (actual, expected, len) {
...
+ * Count the open file descriptors in a given folder
+ *
+ * @param {string} dir folder for counting open file descriptors
+ * @returns {Promise<number>}
+ */
+async function countOpenFileDescriptors (dir) {
+  return new Promise((res, rej) => {
+    exec(`lsof +D '${dir}'`, (error, stdout) => {
+      // if (error) return rej(error)
+      console.log(stdout)
```
Comment (achou11) [inline tests/core-manager.js]: guessing this was for debugging so just a reminder to update if necessary

**Review by achou11 — APPROVED** [review]
