### PR TITLE
chore: Update @mapeo/schema, fix breaking changes related to Icon

### LINKED ISSUE #547: Update @mapeo/schema, fix breaking changes related to Icon schema
## Description
When updating `@mapeo/schema` version, types related to icons will break in relation to [this](https://github.com/digidem/mapeo-schema/pull/174) change. Mainly the issue will be that `pixelDensity` is not present on every icon variant so we would need to filter types for that

## Tasks

- [ ] update types in `src/icon-api.js` and `src/fastify-plugins/icons.js` (13 type errors in two files)
- [ ] update tests if needed (installing `main` branch for mapeo-schema yields no failing tests)

### PR DESCRIPTION
**Pull request by tomasciccola**
This should fix #547 . This PR basically covers breaking changes on mapeo-schema brought by [this](https://github.com/digidem/mapeo-schema/pull/174) (basically removing `pixelDensity` from `Icon`s whose `mimeType` is `"image/svg+xml"`)
Before merging, a new version of @mapeo/schema should be published, and the tar.gz on this branch should be removed

### CODE REVIEW

File: src/icon-api.js [hunk 1]
```diff
@@ -184,16 +174,51 @@ export function getBestVariant(variants, opts) {
 
     // Both variants match desired size, use pixel density to determine preferred match
     if (aSizeDiff === 0 && bSizeDiff === 0) {
-      // Pixel density doesn't matter for svg but prefer lower for consistent results
+      // What to do if asking for an svg and both (a and b) are svgs and have the same size, what criteria do we use?
+      // For now check a and b for mimeType, the only weird case being both svgs
       if (opts.mimeType === 'image/svg+xml') {
-        return a.pixelDensity <= b.pixelDensity ? -1 : 1
+        if (a.mimeType === 'image/svg+xml' && b.mimeType === 'image/png') {
```
Comment (tomasciccola) [inline src/icon-api.js:180]: this probably can be done much cleaner (and I probably got the sort code backwards...).
 I'm basically checking every combination of `mimeType` for a and b with both `opts.mimeType` being png or svg. This is because now svgs don't have a `pixelDensity`

File: src/icon-api.js [hunk 2]
```diff
@@ -182,18 +172,23 @@ export function getBestVariant(variants, opts) {
...
     const bSizeDiff = bSizeNum - wantedSizeNum
 
-    // Both variants match desired size, use pixel density to determine preferred match
+    // Both variants match desired size, use pixel density (when png) to determine preferred match
     if (aSizeDiff === 0 && bSizeDiff === 0) {
-      // Pixel density doesn't matter for svg but prefer lower for consistent results
-      if (opts.mimeType === 'image/svg+xml') {
-        return a.pixelDensity <= b.pixelDensity ? -1 : 1
+      // What to do if asking for an svg and both (a and b) are svgs and have the same size, what criteria do we use?
+      // For now, we don't change sort order
```
Comment (tomasciccola) [inline src/icon-api.js:178]: Does this make sense??

**Comment by tomasciccola** [comment]
mmhm, still need to fix some type errors on the icon unit tests

File: src/fastify-plugins/icons.js [hunk 3]
```diff
@@ -13,12 +13,14 @@ export default fp(iconServerPlugin, {
...
-const VALID_PIXEL_DENSITIES =
-  docSchemas.icon.properties.variants.items.properties.pixelDensity.enum
+const VALID_SIZES = docSchemas.icon.definitions.size.enum
+const VALID_MIME_TYPES = docSchemas.icon.properties.variants.items.oneOf.map(
+  (iconType) => iconType.properties.mimeType.const
+)
+const VALID_PIXEL_DENSITIES = docSchemas.icon.properties.variants.items.oneOf
+  .filter((iconType) => iconType.properties.mimeType.const === 'image/png')
+  /** @ts-ignore using the array.filter as type guard? */
+  .map((pngIcon) => pngIcon.properties.pixelDensity.enum)
```
Comment (EvanHahn) [inline src/fastify-plugins/icons.js:23]: To avoid the `ts-ignore`:

```suggestion
  .map((iconType) =>
    'pixelDensity' in iconType.properties
      ? iconType.properties.pixelDensity.enum
      : []
  )
  .flat()
```

This also lets us add new mime types in the future, and if they have `pixelDensity`, we'll take it.

File: src/icon-api.js (hunk 2 above)
Comment (EvanHahn) [reply src/icon-api.js:178]: Makes sense to me!

File: src/icon-api.js [hunk 4]
```diff
@@ -182,18 +172,23 @@ export function getBestVariant(variants, opts) {
...
+      if (wantedMimeType === 'image/svg+xml') {
+        return 0
+      } else if (
+        wantedMimeType === 'image/png' &&
+        a.mimeType === 'image/png' &&
```
[the remark this answers is not in the document]
Comment (EvanHahn) [reply src/icon-api.js:183]: I think this is fine for now.

**Review by EvanHahn — APPROVED** [review]
LGTM! One small nitpick suggestion.

File: src/fastify-plugins/icons.js [hunk 5]
```diff
@@ -139,15 +147,10 @@ function assertValidSize(value) {
...
+ * @returns {asserts value is import('../icon-api.js').BitmapOpts['pixelDensity']}
  */
 function assertValidPixelDensity(value) {
-  if (
-    !VALID_PIXEL_DENSITIES.includes(
-      // @ts-expect-error
-      value
-    )
-  ) {
+  if (!VALID_PIXEL_DENSITIES.includes(value)) {
```
Comment (EvanHahn) [inline src/fastify-plugins/icons.js:153]: I would fix this error by casting `value` to `any`.

```suggestion
  if (!VALID_PIXEL_DENSITIES.includes(/** @type {any} */ (value))) {
```

**Review by EvanHahn — APPROVED** [review]
Feel free to merge after fixing the type error.

File: src/fastify-plugins/icons.js (hunk 5 above)
Comment (tomasciccola) [reply src/fastify-plugins/icons.js:153]: mhmh, I also needed to change the signature of the fn to  `/** @param {any} value */`

**Comment by tomasciccola** [comment]
@EvanHahn for this to be merged we need a new version of mapeo-schema published. It makes sense that that happens after adding tracks. After that I'll remove the locally built mapeo-schema comitted here and then we can merge
